site_name: Comdex
site_description : An ecosystem of solutions built with an aim of bridging DeFi & CeFi

# Documentation and theme
theme:
  name: material
  custom_dir: resources

  features:
    - tabs
    - navigation.top
    #- instant
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  icon:
  logo: assets/images/logo.svg
  logo_white: assets/images/logo_white.svg
  favicon: assets/images/favicon.ico
  
  # Plugins
plugins:
  - macros
  - search:
        indexing: 'full'
  - minify:
      minify_html: true

  # Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ComdexOfficial
    - icon: fontawesome/brands/telegram
      link: https://t.me/ComdexChat
    - icon: fontawesome/brands/medium
      link: https://comdexofficial.medium.com/


#To add icon to side navigation: name is exact navigation item icon is icon path. 
  nav_links:
    - name: Comdex Overview
      icon: ../assets/images/overview.svg
    - name: Vault
      icon: ../assets/images/overview.svg
    - name: Asset
      icon: ../assets/images/overview.svg
    - name: Oracle
      icon: ../assets/images/overview.svg
    - name: Liquidity
      icon: ../assets/images/overview.svg
    - name: Rewards
      icon: ../assets/images/overview.svg
    - name: Node Setup
      icon: ../assets/images/overview.svg
    - name: Validators
      icon: ../assets/images/overview.svg

# Page tree
nav:
  - Comdex Overview: index.md
  - Vault:
     - Overview : vault.md
     - Concepts: vault_Concepts.md
     - State: vault_State.md
     - Messages: vault_Messages.md
     - Events: vault_Events.md
  - Asset:
     - Overview: Asset_Overview.md
     - State: Asset_State.md
     - Messages: Asset_Messages.md
  - Oracle:
     - Overview: Oracle_Overview.md
     - State: Oracle_State.md
     - Messages: Oracle_Messages.md
  - Liquidity:
     - Overview: Liquidity_Overview.md   
  - Rewards:
     - Overview: Rewards_Overview.md
     - State: Rewards_State.md
     - Messages: Rewards_Messages.md
  - Node Setup:
     - Installation: Node_installation.md
     - Config: Node_config.md
     - TestNet: Node_testnet.md
     - Join Network: Node_join-network.md
  - Validators:
    - Validator Guide: Validator_Guide.md
    - Validator Setup: Validator_Setup.md
    - Validator FAQ: Validator_FAQ.md
    - Security Practices: Validator_Security_Practices.md

extra_css:
  - assets/stylesheets/custom.css
