site_name: Comdex
site_description : An ecosystem of solutions built with an aim of bridging DeFi & CeFi

# Documentation and theme
theme:
  name: material
  custom_dir: resources

  features:
    - tabs
    - navigation.top
    #- instant
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  icon:
  logo: assets/images/logo.svg
  logo_white: assets/images/logo_white.svg
  favicon: assets/images/favicon.ico
  
  # Plugins
plugins:
  - macros
  - search:
        indexing: 'full'
  - minify:
      minify_html: true
  
  # Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ComdexOfficial
    - icon: fontawesome/brands/telegram
      link: https://t.me/ComdexChat
    - icon: fontawesome/brands/medium
      link: https://comdexofficial.medium.com/


#To add icon to side navigation: name is exact navigation item icon is icon path. 
  nav_links:
    - name: Comdex Overview
      icon: ../assets/images/overview.svg
    - name: CDP
      icon: ../assets/images/overview.svg
    - name: Asset
      icon: ../assets/images/overview.svg
    - name: Oracle
      icon: ../assets/images/overview.svg
    - name: Liquidity
      icon: ../assets/images/overview.svg
    - name: Incentives
      icon: ../assets/images/overview.svg

# Page tree
nav:
  - Comdex Overview: index.md
  - CDP:
     - Overview : cdp.md
     - Concepts: cdp_Concepts.md
     - State: cdp_State.md
     - Messages: cdp_Messages.md
     - Events: cdp_Events.md
  - Asset:
     - Overview: Asset_Overview.md
     - State: Asset_State.md
     - Messages: Asset_Messages.md
  - Oracle:
     - Overview: Oracle_Overview.md
     - State: Oracle_State.md
     - Messages: Oracle_Messages.md
  - Liquidity:
     - Overview: Liquidity_Overview.md   
  - Incentives:
     - Overview: Incentive_Overview.md
     - State: Incentive_State.md
     - Messages: Incentive_Messages.md

extra_css:
  - assets/stylesheets/custom.css